### ISSUE TITLE
ScanPal EDA51 , Tapping the "Start Scan"  button Not triggering the scan

### ISSUE THREAD

**Issue by jimpmathew** [hjgode/IntentAPISample#1]
By using the hardware button, everything working fine. But by tapping the "Start Scan"  button not triggering the scan. Is there any settings changes required? I have even tested with the sample APK, but no luck.

**Comment by hjgode** [comment]
This is an issue with Android 8.

Although other say the code needs not to use targetSDKversion higher than 25 to be able to sendBroadcast, for me I had to use the sendImplicitBroadcast workaround.

**Comment by hjgode** [comment]
Code should run on Android 8 too now.
