### ISSUE TITLE
Does it works with N6603 scanner ?

### ISSUE THREAD

**Issue by vekain** [hjgode/IntentAPISample#3]
Hey, I am trying to work with honeywell N6603 scanner. does your repo work with that ?

**Comment by hjgode** [comment]
This API is not related to a scanner modul but to the Android
Honeywell extensions installed on a Honeywell handhaeld.

**Comment by vekain** [comment]
Is there any android sdk available on Internet for N6603 scanner that can work with an android application? Currently blackview B5100 Pro has an inbuilt application that works with that scanner but I am not able to find any sdk regarding that.

**Comment by hjgode** [comment]
The BV5100 Pro by Blackview seems to have no support for N6603 access
by app by Blackview company. Please follow the community thread at
https://bbs.blackview.hk/viewtopic.php?f=17&t=542120&p=994114&hilit=sdk#p994114
and https://bbs.blackview.hk/viewtopic.php?f=17&t=542664.

I would connect ADB to the device and look for events in logcat
regarding barcode scanning. Possibly there is a way to find out what
Blackview did.

For me that device is useless in industrial envirnment as long as
there is no SDK.

**Comment by hjgode** [comment]
Possibly you can download the scanner app of the Blackview and decompile to see how the barcode scanner is used.

Closing topic as it is not honeywell related

**Comment by rompic** [comment]
in case someone is ending up here as well. i dug a little deeper. from the output in the logs it seems as if they run this code:
https://github.com/xuanyuanpang/hwsoftscan/
